# Generated by Django 3.2.16 on 2023-01-16 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my", "0003_auto_20221220_1059"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="jewelry",
        ),
    ]
