# Generated by Django 3.2.16 on 2023-01-23 05:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my", "0005_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="jewelry",
        ),
        migrations.AddField(
            model_name="message",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my.order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="update_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="position",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="core.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="send_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
