# Generated by Django 3.2.16 on 2023-01-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my", "0007_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Корзина",
                to="my.cart",
            ),
            preserve_default=False,
        ),
    ]
