# Generated by Django 3.2.16 on 2023-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my", "0010_auto_20230126_1359"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="order_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="update_time",
            field=models.DateTimeField(null=True),
        ),
    ]
