# Generated by Django 3.2.16 on 2023-02-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my", "0011_auto_20230201_1404"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="Адрес не найден", max_length=300),
        ),
    ]
