# Generated by Django 3.2.16 on 2023-03-21 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my", "0012_order_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="reciever",
        ),
    ]
