# Generated by Django 3.2.16 on 2023-04-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my", "0013_remove_message_reciever"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AddField(
            model_name="profile",
            name="second_name",
            field=models.CharField(default="-", max_length=70),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="-", max_length=70),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="-", max_length=70),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my.profile",
                        verbose_name="Профиль пользователя",
                    ),
                ),
            ],
        ),
    ]
