# Generated by Django 3.2.16 on 2023-04-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my", "0014_auto_20230407_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="my.address",
            ),
        ),
    ]
