# Generated by Django 3.2.16 on 2022-11-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20221103_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.parttype",
            ),
        ),
    ]
