# Generated by Django 3.2.16 on 2022-11-03 14:32


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_part_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jewelry",
            name="parts",
        ),
        migrations.AddField(
            model_name="jewelry",
            name="parts",
            field=models.ManyToManyField(to="core.Part"),
        ),
    ]
