# Generated by Django 3.2.16 on 2022-11-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_auto_20221103_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="materialJSON",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
