# Generated by Django 3.2.16 on 2022-12-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_material_materialjson"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelry",
            name="ispublic",
            field=models.BooleanField(default=False),
        ),
    ]
