# Generated by Django 3.2.16 on 2022-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_jewelry_ispublic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
