# Generated by Django 3.2.16 on 2022-12-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_jewelry_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelry",
            name="preview",
            field=models.ImageField(
                blank=True, upload_to="previews/<django.db.models.fields.BigAutoField>"
            ),
        ),
    ]
