# Generated by Django 3.2.16 on 2023-01-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_jewelry_preview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="coordinates",
        ),
        migrations.AddField(
            model_name="part",
            name="volume",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="producttype",
            name="volumeCoefficient",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="preview",
            field=models.ImageField(blank=True, upload_to="previews/"),
        ),
    ]
