# Generated by Django 3.2.16 on 2023-01-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20230111_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="density",
            field=models.FloatField(default=0, verbose_name="Плотность, кг/м^3"),
        ),
    ]
