# Generated by Django 3.2.16 on 2023-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_material_density"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Стоимость, руб/грамм"
            ),
        ),
    ]
