# Generated by Django 3.2.16 on 2023-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_auto_20230123_1015"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelry",
            name="cost",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="jewelry",
            name="weight",
            field=models.FloatField(default=0, null=True),
        ),
    ]
