# Generated by Django 3.2.16 on 2023-02-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_auto_20230201_1347"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelry",
            name="is_editable",
            field=models.BooleanField(default=True),
        ),
    ]
