# Generated by Django 3.2.16 on 2023-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_jewelry_is_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
