# Generated by Django 3.2.16 on 2023-04-04 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="preview",
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="cost",
            field=models.FloatField(default=0, null=True, verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="is_editable",
            field=models.BooleanField(default=True, verbose_name="Редактируемо?"),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="ispublic",
            field=models.BooleanField(
                default=False,
                help_text="Характеризует необходимость отображения изделия в каталоге.",
                verbose_name="Публичное изделие?",
            ),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="material",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="parts",
            field=models.ManyToManyField(
                help_text='Поле "многие ко многим", необходимый набор деталей выбирается нажатием.',
                to="core.Part",
                verbose_name="Детали",
            ),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="preview",
            field=models.ImageField(
                blank=True, upload_to="previews/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.producttype",
                verbose_name="Тип изделия",
            ),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="update_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                verbose_name="Время обновления",
            ),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="jewelry",
            name="weight",
            field=models.FloatField(default=0, null=True, verbose_name="Вес"),
        ),
        migrations.AlterField(
            model_name="material",
            name="materialJSON",
            field=models.JSONField(
                help_text="Материал, заданный в форме JSON-строки, оформленной по стандартам ThreeJS для материалов.",
                verbose_name="JSON-представление материала для конструктора",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="material",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="material",
            name="update_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                verbose_name="Время обновления",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="ModelFile",
            field=models.FileField(
                help_text="В формате .obj",
                upload_to="parts/",
                verbose_name="Файл модели",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.parttype",
                verbose_name="Тип детали",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="part",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="part",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Время изменения"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="volume",
            field=models.FloatField(
                default=0, help_text="Берется из 3d-редактора", verbose_name="Объем"
            ),
        ),
        migrations.AlterField(
            model_name="parttype",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="parttype",
            name="productType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.producttype",
                verbose_name="Тип изделия",
            ),
        ),
        migrations.AlterField(
            model_name="parttype",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="parttype",
            name="update_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                verbose_name="Время обновления",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="update_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                verbose_name="Время обновления",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="volumeCoefficient",
            field=models.FloatField(
                default=0,
                help_text="Вычисляется как отношение объема модели среднего по размеру изделия, взятое из 3d-редактора к объему изделия реалистичных размеров.",
                verbose_name="Коэффициент объема",
            ),
        ),
    ]
